version: '3.8'

services:
  # Serviço do Back-end em Python
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/app

  # Serviço do Front-end em Angular
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que a máquina local delete os módulos do contêiner
    depends_on:
      - backend